### ISSUE TITLE
Make the app work offline

### ISSUE THREAD

**Issue by ghost** [pedrocoutinhosilva/shiny.pwa#1]
When the app is offline it appears the message "the app is offline...".
How can I make the app work as other apps with service worker? functioning normally offline...
Congratulations for the great package!

**Comment by pedrocoutinhosilva** [comment]
Thank you!, I'm glad you got some usage out of it :) 

Unfortunately when it comes to fully offline functionality, shiny isn't there yet. Because of how shiny works under the hood, it requires a constant active connection to a server running the R session, using a web socket connection. An offline version would require having R running in the browser somehow (web assembly for example) and connecting this browser R server to the web socket connection. There's been some talks about how to achieve this, but in general no progress has been done in the last year that i know of.

Using shiny.pwa right now you can technically have a javascript app instead of the offline message by creating and passing a  `offline_template`, but any functionality here would need a separate application build with non shiny technologies.

I will keep an eye out for possible progress here, but right now its not yet an option and requires a breakthrough in having shiny:
 - not be dependent on the web socket connection 
 - Be able to process server side functionality without a server connection
