### ISSUE TITLE
PWA icon doesn't appear to be working

### ISSUE THREAD

**Issue by nathhenry3** [pedrocoutinhosilva/shiny.pwa#3]
Hi there,

I can't seem to get the PWA icon to work for my app. 

Here's the code I'm using in ui.R:

pwa("https://website_name,
          "website_name",
          output="www",
          color='#000000',
          icon=here::here('www', 'website_name_icon_512x512.png') # Icon is definitely 512x512px, and in the right place
          )

Otherwise, the PWA works fine. Any idea what could be wrong?

Thanks!

**Comment by pedrocoutinhosilva** [comment]
Hi! Thank you for reaching out!

The issue here seems related to the `here` function, it will return a absolute path to the icon file, but `pwa()` requires only the relative path from the project root:

```
pwa("https://website_name,
  "website_name",
  output="www",
  color='#0',
  icon="www/website_name_icon_512x512.png" # assuming your icon is in the www folder in your project
```

In any case I will make sure to update the documentation to make it more clear (I will also include a new example with a custom icon for the next release)

Thank you, and let me know if it works for you!

**Comment by nathhenry3** [comment]
Ah, that makes sense. Thank you very much! And yes, it works perfectly now
