### ISSUE TITLE
I run file inside examples folder and i also run my file Both don't working

### ISSUE THREAD

**Issue by ravinder387** [pedrocoutinhosilva/shiny.pwa#7]
![2022-04-25 (1)](https://user-images.githubusercontent.com/21985515/165033780-7c188cf6-941a-4dda-ab5a-dbb1e2fb1bdf.png)

**Comment by pedrocoutinhosilva** [comment]
Hi!

Because of the limitations of PWAs, testing the behavior locally is complicated... To see the PWA in action it requires:
 - The page to be served under https protocol
 - The page to be served with a URL instead of simply a IP 

Having both of these locally is a bit of a painful process, but one quick way to test it is to deploy to shinyapps.io, since it provides both at once (remember to update the url in the `pwa` function)

Let me know if that works for you!

**Comment by pedrocoutinhosilva** [comment]
Closing for now, feel free to reopen if you still have any issues!
